### ISSUE TITLE
Undocumented global CSS handling

### ISSUE THREAD

**Issue by thearnica** [dlehmhus/next-with-linaria#11]
Hey, thank you for the beautiful solution and unblocking my Next13 experiments.

So far I've noticed only one "big" problem (the other one is something about linaria vs webpack cache) related to global css and the expectations for css modules - aka "pure selectors"

Long story short - you have [undocumented file pattern](https://github.com/dlehmhus/next-with-linaria/blob/main/src/loaders/transformLoader.ts#L152) enabling non-pure selectors and the pattern is not really "sound" - I can imagine a file named `css-reset.global.ts`, but not `css-reset.linaria.global.ts`

Wondering if pattern can be changed a little bit and the solution documented.

**Comment by dlehmhus** [comment]
Hey @thearnica, I'm glad to hear that it helps your experiments. Unfotuantially I'm not quite sure if I got the issue, could you elaborate a bit more? I tried to document the rule [here](https://github.com/dlehmhus/next-with-linaria#global-styles-restrictions). Is there anything that could have been documented better?

**Comment by thearnica** [comment]
🙃 yep, everything is clearly documented. Now I am drinking the second cup of a coffee and thinking how did I miss that

Look like my issue was resolved 🤗, thank you
