### ISSUE TITLE
CSS collected from other routes when they share dependencies

### ISSUE THREAD

**Issue by joshwcomeau** [dlehmhus/next-with-linaria#26]
Hi there! 

I've been using next-with-linaria on my blog, and I noticed that quite a bit of unused CSS was getting loaded. I spent some time digging into it today, and I figured out what's happening (though I don't know if it's a problem with `next-with-linaria`, or Linaria itself).

I created a minimum reproduction:
https://github.com/joshwcomeau/linaria-code-splitting-repro

The README has a lot of information, but I'll summarize here.

It appears as though independent routes will have their CSS combined if they both import the same shared components. For example, suppose we have two routes and a single shared component:

```
├── app/
│   ├── about/
│   │   └── page.tsx
│   └── page.tsx
└── components/
    └── Button.tsx
```

Both the homepage (`/`) and the about page (`/about`) have their own styled components with Linaria, and they both import the Button component, which has its own styles.

When visiting the homepage, the generated CSS file has the homepage styles and the button styles, _but also the about page styles_. Even though the homepage doesn't import the about page.

Curiously, the issue only occurs in production. In development, the CSS files are generated the way I'd expect.

These tests were performed on macOS Sonoma 14.5, with Node v20.16.0, and the latest version of all relevant dependencies.

Let me know if you need any more info from me!

**Comment by dlehmhus** [comment]
@joshwcomeau thanks for the report. The issue has nothing to do with `next-with-linaria` or `linaria` but is a Next.js issue or optimization?! I don't know how the code splitting is implemented in detail, therefore I can not say if this is a bug or a feature :P When you use `next-with-linaria` you actually use [CSS modules](https://nextjs.org/docs/pages/building-your-application/styling/css-modules) (created from the CSS-in-JS at build time). To showcase this,  I removed everything linaria-related from your example and used CSS Modules directly. With the same result. You can take a look here yourself: https://github.com/dlehmhus/linaria-code-splitting-repro

**Comment by dlehmhus** [comment]
Quick Follow-Up - it looks like you are not the only one: https://github.com/vercel/next.js/discussions/70168

**Comment by joshwcomeau** [comment]
Hi @dlehmhus,

Ah, that's interesting! I actually did test this with plain CSS modules and I _did_ see the correct code-splitting, but maybe I accidentally tested in dev rather than prod. Sorry for the false alarm!
