### ISSUE TITLE
Module build failed on windows. Something is wrong with paths

### ISSUE THREAD

**Issue by astrovpls** [dlehmhus/next-with-linaria#3]
Got this webpack error when building project on windows. MacOS is ok though

`
error - C:UsersXxxYyyZzzcomponentsmasonrymasonry.linaria.module.css
Module build failed: UnhandledSchemeError: Reading from "C:UsersXxxYyyZzzcomponentsmasonrymasonry.linaria.module.css" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "c:" URIs.
`

Paths are messed up for some reason.
Issue can be reproduced with [StackBlitz](https://stackblitz.com/edit/next-with-linaria?file=app%2Fpage.tsx) example from readme.

**Comment by dlehmhus** [comment]
Hey @astrovpls, thanks for reporting. I will take a look at it. But maybe it's the universe telling you to use MacOS 😉

**Comment by astrovpls** [comment]
I am more and more convinced of this every day 🙃. Thanks for the quick reply!

**Comment by dlehmhus** [comment]
@astrovpls could you check if the issues still exists in the latest canary? You can install it by running 
```sh
npm i next-with-linaria@canary
```

**Comment by astrovpls** [comment]
@dlehmhus I see no issues in canary
