### ISSUE TITLE
CSS not loading until after the page is rendered Next 13

### ISSUE THREAD

**Issue by ghost** [dlehmhus/next-with-linaria#7]
I am using the next config set up in the next-with-linaria instructions for Next 13 but the css is not being loaded before the page is being rendered. This results in a flash of chaos on the page for a split second on initial load. 

Is there something I can do in the config to fix this ? 

Thanks for all advice.

**Comment by dlehmhus** [comment]
Hey @Adamskoullos, could you provide a minimal reproducible example of your issue? In general, the expected behavior should be similar to [normal CSS Modules](https://beta.nextjs.org/docs/styling/css-modules) because that is what the babel plugin does, turning your CSS-in-JS into CSS Modules!

**Comment by Adamskoullos** [comment]
Thank you for coming back to me @dlehmhus , I cannot share the code but below are the main files...I hope I just have something out....all advice welcome.

To elaborate, roughly every 5 - 10 initial loads, the page gets rendered before the css and all icons and images fill the screen for a split second. I do not know if this is just a Next 13 thing or the integration between Next 13 and this package. I appreciate your thoughts.

At the moment I am using a state switch giving the page some time before showing content components.

Let me know if there is anything else I can share. Thank you

** Next.config:
```
const withLinaria = require("next-with-linaria");

/** @type {import('next-with-linaria').LinariaConfig} */
const nextConfig = {
  experimental: {
    appDir: true,
  },
  images: {
    remotePatterns: [omitted],
  },
};

module.exports = withLinaria(nextConfig);
```

** package.json:
```
{
  "name": "",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@linaria/babel-preset": "^4.3.2",
    "@linaria/core": "^4.2.4",
    "@linaria/react": "^4.3.2",
    "@next/font": "13.1.1",
    "@reduxjs/toolkit": "^1.9.1",
    "@types/node": "18.11.18",
    "@types/react": "18.0.26",
    "@types/react-dom": "18.0.10",
    "eslint": "8.30.0",
    "eslint-config-next": "13.1.1",
    "next": "13.1.1",
    "next-with-linaria": "^0.3.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-redux": "^8.0.5",
    "socket.io-client": "^4.5.4",
    "typescript": "4.9.4"
  },
  "devDependencies": {
    "@redux-devtools/core": "^3.13.1"
  },
  "optionalDependencies": {
    "bufferutil": "^4.0.7",
    "utf-8-validate": "^5.0.10"
  }
}
```


** tsconfig:
```{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}```

**Comment by dlehmhus** [comment]
Unfortunately, without anything to look at, it is hard to give any good pointers! It kinda sounds like that in those cases the loading of the CSS is not blocking the first paint of the page. But I'm not sure why this would happen in your case. In general, all the Linaria CSS is turned into real CSS files at build time. So there is really no involvement of Linaria when your Next.js server is running in production mode!

> At the moment I am using a state switch giving the page some time before showing content components.

That really defeats the purpose of SSR, I would say. It definitely shouldn't be necessary when using Next.js! I would recommend that you try to create a small example project to showcase that issue.

**Comment by ghost** [comment]
Yes indeed, thank you for your thoughts, I appreciate it. I will continue my investigation. Kind regards

**Comment by dlehmhus** [comment]
@Adamskoullos it seems you are [not the only one](https://twitter.com/timneutkens/status/1627595924514930689?s=20) with the FOUC issues. Hopefully, they will be fixed by Next.js soon. I'm closing this issue since this Webpack loader can't do much about it.
